server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    default-encoding: UTF-8
    username: 15481079lee@gmail.com
    password: Dlwlsgh1!
    tls: true
    setTLS: true
    properties.mail.smtp:
      ssl.trust: smtp.gmail.com
      start.enable: true
      auth: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    app:
      sample:
        message:
          AuditingFilter: DEBUG
          SecurityChecker: DEBUG
          MessageService: DEBUG